# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

common: &common
  adapter: postgresql
  encoding: unicode
  username: bulletshot60
  password: 
  host: localhost
  pool: 5

development:
  <<: *common
  database: doe_fuel
  
test:
  <<: *common
  database: doe_fuel_test

production:
  adapter: postgresql